name: "Semantic Release Action"
description: "Runs Semantic Release"

inputs:
  version:
    default: "23.0.2"
    description: "npm version of semantic-release to use"
  plugins:
    default: ""
    description: "semantic-release plugins to install"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - run: "npm i -g semantic-release@${{ inputs.version }} ${{ inputs.plugins }}"
      shell: bash

    - run: "npx semantic-release"
      shell: bash
