name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: joaofnds/semantic-release-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
